spring.application.name=pijulcel_app
server.address=0.0.0.0
server.port=${SERVER_PORT:8081}

media.location=${MEDIA_LOCATION:uploads}
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=60MB

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pijulcel_app}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}